services:
  - type: web
    name: gatemate_backup-4
    env: python
    plan: free
    pythonVersion: 3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app


Email: raj1@gmail.com
Password: 1234
